### Codetable代码表
在每个HDB数据文件中，对每个标的的静态基本信息，用hdb.Codetable对象来描述，该对象包括以下四个属性：

    symbols 				# 标的代码列表
    total_items_num       # 总数据条目数
    type_items_nums  		# 各种类型的数据条目数
    data 				   # 自定义数据，数据类型通过hdb.DataType对象描述，用于存放代码对应的静态基础信息。可以通过hdb.File.ci_type.items_data(data)解析


### DataItem数据记录
在HDB文件中，除了记录代码基础信息的代码表数据之外，其他数据都是异构的时序数据DataItem。DataItem中前五个字段是所有数据共有的，第六个字段因数据类型而异，其结构如下：

    symbol					# 标的代码
    trading_day             # 交易日
    local_time              # 本地时间戳，Unix时间,1970-1-1到当前时间经过的毫秒数
    index                 # 该代码在该数据文件全量代码表中的索引
    time_point_seq_no		# 该数据条目在该时间点的所有数据条目中的序号。在一个数据文件中，同一个时间点可能会有多条数据记录，我们通过该字段来标志这些记录的先后次序
    type_id       			# 数据类型id。即该数据类型在当前数据文件的数据 类型数组中的位置，系统生成参数
    data 					  # 自定义数据，数据类型通过hdb.DataType对象描述，可以通过hdb.File.data_types[type_id].items_data(data)解析 

### data自定义数据类型
data的数据类型由hdb.DataType来描述。该对象主要有两个属性：

    DataType.name       #数据类型名称。
    DataType.fields      #数据类型的所有字段组成的列表，列表元素为hdb.DataField对象，用于描述字段的详细属性。
    
#### 自定义数据类型（hdb.DataType）的构造方法
自定义数据类型可以通过  
```hdb.DataType(name, fields)
```
来创建一个自定义数据类型。  
参数：

    name     #数据类型名  
    fields    #字段列表，列表元素为hdb.DataField对象，用于描述该数据类型的各个字段的属性。

返回：hdb.DataType对象。  

例如：定义一个k线数据类型，类型取名为kline, 该数据类型包括“开盘价”、“收盘价”、“最高价”、“最低价”四个字段。利用hdb.DataField方法为每个字段生成一个hdb.DataField对象，将其添加进列表fields中，然后调用：
```hdb.DataType("kline",fields)```  
即可生成一个名为kline的自定义数据类型。  

#### 自定义数据类型（hdb.DataType）的解析方法
通常我们通过ReadTask.read()读取到的数据中，其data部分是一个地址，需要通过hdb.DataType.items_data()方法来解析。例如：
```
import hdb
db = hdb.DB(r"X:\hdb_data")
file = db.open_file(r"marketdata\tick_20220506", mode="r")
task = file.open_read_task(symbols=['SH.600000'], types=['SecurityTick'])
items = task.read()
data_type = file.data_types[items['type_id'][0]]
data = data_type.items_data(items['data'])
```
    

#### 自定义数据类型数组单个字段信息（hdb.DataField） 
自定义数据类型数组单个字段主要由hdb.DataField描述。其主要属性如下：


    DataField.name 				# 字段名
    DataField.type 				# 字段类型（支持的选项见hdb.FieldType）
    DataField.encode_op 		# 字段压缩操作（支持的选项见附录hdb.FieldEncodeOp）
    DataField.size 				# 数组长度
    DataField.flags 			# 额外压缩字段，1表示启用，0表示不启用。该字段为可选字段，即当新的一条记录中该字段的值相对于当前记录中该字段值保持不变时，新的记录中可在压缩编码时跳过该字段。一般除了我们确定基本上每条记录中都会更新的字段，比如时间字段，其它字段我们都可以设置该选项。

#### hdb.FieldType
   
|字段类型|说明|
|:-|:-|
|FieldType.Char|字符类型，长度1字节|
|FieldType.Short|短整型，长度2字节|
|FieldType.UShort|无符号短整型，长度2字节|
|FieldType.Int|整型，长度4字节|
|FieldType.UInt|无符号整型，长度4字节|
|FieldType.Long|长整型，长度8字节|
|FieldType.ULong|无符号长整型，长度8字节|
|FieldType.Float|单精度浮点数，长度4字节|
|FieldType.Double|双精度浮点数，长度8字节|
|FieldType.CharArray|字符数组|
|FieldType.ZeroTermCharArray|以0结尾的字符数组|
|FieldType.SpaceTermCharArray|以空格结尾的字符数组|
|FieldType.IntArray|整数数组|
|FieldType.ZeroTermIntArray|以0结尾的整数数组|
|FieldType.UIntArray|无符号整数数组|
|FieldType.ZeroTermUIntArray|以0结尾的无符号整数数组|
|FieldType.LongArray|长整数数组|
|FieldType.ZeroTermLongArray|以0结尾的长整数数组|
|FieldType.ULongArray|无符号长整数数组|
|FieldType.ZeroTermULongArray|以0结尾的无符号长整数数组|

####  hdb.FieldEncodeOp
  
    FieldEncodeOp.Raw    #不压缩，即直接拷贝该字段原始数据。
    FieldEncodeOp.ValueCompress  #值压缩，即对数值进行压缩(Varint编码)。注意，FieldType的Char与CharArray不支持该压缩编码方式。  
    FieldEncodeOp.ValueIncCompress #增量值压缩，即对该字段相对于上一条记录的增量数值进行压缩(Varint编码)。注意，FieldType的Char、CharArray、ZeroTermCharArray、SpaceTermCharArray不支持该压缩编码方式。


#### 字段信息（hdb.DataField）的构造方法
HDB作为一个自描述文件，任意数据类型的任意字段都由hdb.DataField对象来描述，该对象可以通过    
``` hdb.DataField(name, type, encode_op, size=0, flags=0)```
构造。  
 
 
例如：股票的k线数据至少包括“开盘价”、“收盘价”、“最高价”、“最低价”四个字段。以开盘价为例，字段名取为open，字段类型用无符号长整型，数组长度为一，则可以调用:  
```hdb.DataFiled('open',hdb.FieldType.ULong,hdb.FieldEncodeOp.ValueIncCompress,1,0)```   
来创建开盘价的描述字段。

 
## HDB读写(本地/远程连接服务器)功能相关API介绍
HDB读写本地和远程两种模式：本地模式读取本地HDB文件来获取行情；远程模式是指连接远端的服务器来获取数据。hdb模块有以下10个类
 
 + hdb.Client
 + hdb.Codetable
 + hdb.DB
 + hdb.DataField
 + hdb.DataFrame
 + hdb.File
 + hdb.ReadTask
 
### hdb.Client(host, port, username, pwd, op_timeout=15000)
方法描述：
    
    连接远程的HDBServer,并创建hdb.Client对象。  
参数：  
 
     host：HDBServer的IP地址；  
     port: HDBServer的端口；  
     username: 用户名；  
     pwd：密码；  
     op_timeout：连接超时时间，单位毫秒，默认值15000毫秒。  
返回：
    
    hdb.Client对象。
 
#### Client.open_file(path, req_ct_data=False)
方法描述：

    打开服务器端文件。  
参数：  
 
     path：服务端文件的路径，即相对于根目录的文件相对路径，当需要打开内存缓存数据文件时，文件路径需加上前缀memory/  
     req_ct_data: 指定是否需要代码表的data字段(即HCodeInfo的data字段)，默认不需要，如果需要则改参数为True,不需要时候就给默认参数，可以减少网络传输消耗
 
返回：

    hdb.File对象
 
#### Client.close() 
方法描述：
    
    主动关闭client连接，关闭了客户端连接后，再去open_file会抛出runtime error。


### hdb.DB(db_path)
方法描述：
    
    传入本地HDB文件数据库的存放目录，打开该目录，并创建hdb.DB对象。  
参数描述：

    db_path：本地HDB文件数据库的存放目录  

返回：

    hdb.DB对象  

#### DB.create_file(path, ci_type=None, data_types, packet_size=131072)
方法描述：

    在指定目录下创建HDB文件。  
参数描述：

    path: HDB文件的创建路径  
    ci_type：HDB文件中codeinfo数据类型，变量类型为hdb.DataType，默认为None  
    data_types：HDB文件中各种自定义的数据类型，变量类型为List[hdb.DataType]  
    packet_size：HDB文件的块大小。HDB的API读取数据是按块存储，按块读取的。该值越大，读取速度越快，但同时占用的磁盘空间与读取时占用的内存空间也就越大。  
返回：
    
    hdb.File对象  

#### DB.get_trading_days(begin_date, end_date, holiday_file= 'download/holidayinfo.txt')
方法描述：
    
    获取[begin_date,end_date]这个区间内的全部交易日，注意该区间为闭区间。  
参数描述：

    begin_date：开始日期,格式为YYYYMMDD,类型为int,例如：2022年8月10日表示为20220810。
    end_date：结束日期，格式同上。
    holiday_file：记录了交易日历的文件，一般在db_path下面的"download\holidayinfo.txt"路径下。  
返回：

    [begin_date,end_date]之间所有的交易日  

#### DB.open_file(path, mode = 'r')
方法描述：
    
    打开指定的HDB文件  
参数描述：

    path：文件路径。沪深A股与商品期货期权的HDB文件存放于db_path下的marketdata/目录下。  
    mode：支持 'r'和'r+'，'r'表示只读模式，'r+'表示读写模式。  
返回：
    
    hdb.File对象

    

 ### hdb.File 
 对象描述：
     
     无构造方法。该对象只能由调用hdb.DB.openfile、hdb.Client.open_file、hdb.DB.create_file三个方法返回。返回后，会把ci_type、data_types、codetable三个属性的信息读取到本地，供后续使用。

 
 #### File.ci_type
 属性描述：
     
     hdb.DataType对象，用来描述文件中的代码基础信息的数据类型，注意这里描述的是数据类型。  
 
 #### File.data_types
 属性描述：
 
     hdb.DataType对象组成的list，用于描述HDB文件中包含的数据类型。  
 
 #### File.codetable
 属性描述：
 
     hdb.Codetable对象，描述文件中的代码表信息。  
 
 #### File.close()
 方法描述：
     
     关闭文件。  
 
 #### File.get_all_codelists()
 方法描述：
 
     返回文件中的所有代码表的名称，例如：“QSAG”表示沪深A股的全部代码表。  
 
 返回：
     
     代码表名称，str组成的list。  
 
 #### File.get_codelist(cl_name,no_data=True)
 方法描述：
 
     根据代码表名称（cl_name），返回对应的代码表。  
 
 参数：
 
     cl_name：代码表名称cl_name。  
     no_data：是否返回数据，默认不返回数据，即返回的hdb.Codetable对象的data属性为空。  
 
 返回：
     
     hdb.Codetable对象。  
 
 #### File.open_read_task(begin_time = datetime.datetime(1970, 1, 1, 8, 0), end_time = datetime.datetime(1970, 1, 1, 8, 0), symbols, types, offset: int = 0, thread_num = 4)
 方法描述：
 
     建立一个读取任务，读取指定时间段，任意代码列表，任意类型集合的数据。  
 参数：  
 
     begin_time：开始日期时间，datetime类型，默认值为datetime.datetime(1970, 1, 1, 8, 0)。  
     end_time：结束日期时间，datetime类型，默认值为datetim.datetime(1970, 1, 1, 8, 0)。  
     symbols：读取的股票代码列表。例如：```["SH.600000","SZ.000001"]```表示读取“SH.600000”和“SZ.000001”两支股票数据。
     types：读取的数据类型。例如：```["SHStepTrade","SZStepTrade"]```表示读取上海逐笔成交数据与深圳逐笔成交数据。  
     offset：偏移量，默认值为0。
     thread_num：读取线程数，即可以使用多线程读取数据，加快读取速度，默认值为4。  
 
 返回：
 
     hdb.ReadTask对象
 

 #### File. read(symbols, type, fields, begin_time = datetime.datetime(1970, 1, 1, 8, 0), end_time = datetime.datetime(1970, 1, 1, 8, 0), thread_num = 4)
方法描述：
    
    将指定代码列表，指定时间段，某单一类型，指定字段列表的数据读取为hdb.DataFrame。  
参数：

    symbols：代码列表  
    type：数据类型  
    fields：字段列表，该方法可以指定读取特定一些的字段。  
    begin_time：开始日期时间  
    end_time：结束日期时间  
    thread_num：线程数， 即可开启多线程读取数据， 默认值为4。  
返回：

    hdb.DataFrame  

#### File.write(type_id, symbols, local_times, trading_days, data)
方法描述：
    
    将数据写入HDB文件。
参数：

    type_id：类型ID  
    symbols：代码列表  
    local_times：本地时间戳  
    trading_days：交易日  
    data：要写入的数据  

### hdb.ReadTask
对象描述：
    
    无构造方法。该对象只能由调用hdb.File.open_read_task返回。

#### ReadTask.close()
方法描述：

    关闭读取任务。

#### ReadTask.read(max_count=0)
方法描述：
    
    从读取任务中获取读取结果。  
参数：
    
    max_count：最大一次性读取记录条数。  
    
## 附录
    
### code_list_name部分代码列表名称
|选项|说明|
|:-|:-|
|QSAG|全市场A股|
|SHAG|上交所A股|
|SZAG|深交所A股|
|SHAGZT|上海A股涨停|
|SZAGZT|深圳A股涨停|
|QSJJ|全市场基金|
|SHJJ|上海基金|
|SZJJ|深圳基金|
|QSZQ|全市场债券|
|SHZQ|上海债券|
|SZZQ|深圳债券|
|SHNHG|上海逆回购|
|SZNHG|深圳逆回购|
|SHOP|上海期权|
|SZOP|深圳期权|


###  服务器中文件介绍

| 文件夹       | 文件夹中文件名                                               | 介绍                                                         |
| ------------ | ------------------------------------------------------------ | ------------------------------------------------------------ |
| marketdata/  | tick_date(例，tick_20200511)                                 | tick数据，包含CodeInfo、(CodeList)、<br>DataItem(SecurityTick、IndexTick、FuturesTick、OptionsTick、SHStepTrade、SZStepTrade、SZStepOrder、OrderQueueItem、SZOptionsTick) |
| bar/         | day_bar_year(例，day_bar_2020);<br>min_bar_date(例，min_bar_20200511) | K线数据（按日，按分钟）                                      |
| baseinfo/    | SecurityInfo_date(例，SecurityInfo_20200511)                 | 详细的证券代码基本信息数据                                   |
| fundmentals/ | qxdata_year(例，qxdata_2020)                                 | 除息数据                                                     |

### 服务器中Tick数据介绍

| Tick数据       | 名字含义         |
| -------------- | ---------------- |
| CodeList       | 代码列表         |
| CodeInfo       | 代码基本信息     |
| SecurityTick   | 证券Tick数据     |
| IndexTick      | 指数Tick数据     |
| FuturesTick    | 期货Tick数据     |
| OptionsTick    | 期权Tick数据     |
| SHStepTrade    | 上海逐笔成交数据 |
| SZStepTrade    | 深圳逐笔成交数据 |
| SZStepOrder    | 深圳逐笔委托数据 |
| OrderQueueItem | 委托队列数据     |
| SZOptionsTick  | 深圳期权Tick数据 |

## 样列

#### 获取hdb文件中数据类型

In [9]:
import hdb
db = hdb.DB(r"E:\data\bar\min_bar")
file = db.open_file(r"2005\min_bar_20050121", mode="r")
#数据类型数组
data_types = file.data_types
for data_type in data_types:
    print(data_type.name)
###打印各个类型名称

SecurityKdata

In [10]:
#SecurityTick的各个字段
for field in data_types[0].fields:
    print(field.name)

date
time
pre_close
open
high
low
close
volume
turnover
open_interest
pre_settle_price
settle_price

#### 读取代码信息

In [11]:
print("打印类型名：")
print(file.ci_type.name)
print()
print("打印基础信息字段：")
print(file.ci_type.dtype)

打印类型名：
HCodeInfo

打印基础信息字段：
[('sec_type', '<i4'), ('sec_name', 'S24'), ('date', '<i4'), ('high_limited', '<u4'), ('low_limited', '<u4'), ('multiplier', '<i4'), ('margin_ratio', '<i4'), ('price_tick', '<i4'), ('capital', '<i8'), ('cap_change_date', '<u4'), ('trade_date_in', '<u4'), ('trade_date_out', '<u4'), ('is_halt', 'i1'), ('margin_unit', '<u4'), ('margin_ratio_param1', '<i4'), ('margin_ratio_param2', '<i4')]

In [12]:
file.codetable.symbols

['SH.000001',
 'SH.000002',
 'SH.000003',
 'SH.000004',
 'SH.000005',
 'SH.000006',
 'SH.000007',
 'SH.000008',
 'SH.000010',
 'SH.000011',
 'SH.000012',
 'SH.000015',
 'SH.000016',
 'SH.600000',
 'SH.600001',
 'SH.600002',
 'SH.600003',
 'SH.600004',
 'SH.600005',
 'SH.600006',
 'SH.600007',
 'SH.600008',
 'SH.600009',
 'SH.600010',
 'SH.600011',
 'SH.600012',
 'SH.600015',
 'SH.600016',
 'SH.600018',
 'SH.600019',
 'SH.600020',
 'SH.600021',
 'SH.600022',
 'SH.600026',
 'SH.600028',
 'SH.600029',
 'SH.600030',
 'SH.600031',
 'SH.600033',
 'SH.600035',
 'SH.600036',
 'SH.600037',
 'SH.600038',
 'SH.600039',
 'SH.600050',
 'SH.600051',
 'SH.600052',
 'SH.600053',
 'SH.600054',
 'SH.600055',
 'SH.600056',
 'SH.600057',
 'SH.600058',
 'SH.600059',
 'SH.600060',
 'SH.600061',
 'SH.600062',
 'SH.600063',
 'SH.600064',
 'SH.600065',
 'SH.600066',
 'SH.600067',
 'SH.600068',
 'SH.600069',
 'SH.600070',
 'SH.600071',
 'SH.600072',
 'SH.600073',
 'SH.600074',
 'SH.600075',
 'SH.600076',
 'SH.600077',
 'SH.600078',
 'SH.600079',
 'SH.600080',
 'SH.600081',
 'SH.600082',
 'SH.600083',
 'SH.600084',
 'SH.600085',
 'SH.600086',
 'SH.600087',
 'SH.600088',
 'SH.600089',
 'SH.600090',
 'SH.600091',
 'SH.600092',
 'SH.600093',
 'SH.600094',
 'SH.600095',
 'SH.600096',
 'SH.600097',
 'SH.600098',
 'SH.600099',
 'SH.600100',
 'SH.600101',
 'SH.600102',
 'SH.600103',
 'SH.600104',
 'SH.600105',
 'SH.600106',
 'SH.600107',
 'SH.600108',
 'SH.600109',
 'SH.600110',
 'SH.600111',
 'SH.600112',
 'SH.600113',
 'SH.600114',
 'SH.600115',
 'SH.600116',
 'SH.600117',
 'SH.600118',
 'SH.600119',
 'SH.600120',
 'SH.600121',
 'SH.600122',
 'SH.600123',
 'SH.600125',
 'SH.600126',
 'SH.600127',
 'SH.600128',
 'SH.600129',
 'SH.600130',
 'SH.600131',
 'SH.600132',
 'SH.600133',
 'SH.600135',
 'SH.600136',
 'SH.600137',
 'SH.600138',
 'SH.600139',
 'SH.600141',
 'SH.600143',
 'SH.600145',
 'SH.600146',
 'SH.600148',
 'SH.600149',
 'SH.600150',
 'SH.600151',
 'SH.600152',
 'SH.600153',
 'SH.600155',
 'SH.600156',
 'SH.600157',
 'SH.600158',
 'SH.600159',
 'SH.600160',
 'SH.600161',
 'SH.600162',
 'SH.600163',
 'SH.600165',
 'SH.600166',
 'SH.600167',
 'SH.600168',
 'SH.600169',
 'SH.600170',
 'SH.600171',
 'SH.600172',
 'SH.600173',
 'SH.600175',
 'SH.600176',
 'SH.600177',
 'SH.600178',
 'SH.600179',
 'SH.600180',
 'SH.600181',
 'SH.600182',
 'SH.600183',
 'SH.600184',
 'SH.600185',
 'SH.600186',
 'SH.600187',
 'SH.600188',
 'SH.600189',
 'SH.600190',
 'SH.600191',
 'SH.600192',
 'SH.600193',
 'SH.600195',
 'SH.600196',
 'SH.600197',
 'SH.600198',
 'SH.600199',
 'SH.600200',
 'SH.600201',
 'SH.600202',
 'SH.600203',
 'SH.600205',
 'SH.600206',
 'SH.600207',
 'SH.600208',
 'SH.600209',
 'SH.600210',
 'SH.600211',
 'SH.600212',
 'SH.600213',
 'SH.600215',
 'SH.600216',
 'SH.600217',
 'SH.600218',
 'SH.600219',
 'SH.600220',
 'SH.600221',
 'SH.600222',
 'SH.600223',
 'SH.600225',
 'SH.600226',
 'SH.600227',
 'SH.600228',
 'SH.600229',
 'SH.600230',
 'SH.600231',
 'SH.600232',
 'SH.600233',
 'SH.600234',
 'SH.600235',
 'SH.600236',
 'SH.600237',
 'SH.600238',
 'SH.600239',
 'SH.600240',
 'SH.600241',
 'SH.600242',
 'SH.600243',
 'SH.600246',
 'SH.600247',
 'SH.600248',
 'SH.600249',
 'SH.600250',
 'SH.600251',
 'SH.600252',
 'SH.600253',
 'SH.600255',
 'SH.600256',
 'SH.600257',
 'SH.600258',
 'SH.600259',
 'SH.600260',
 'SH.600261',
 'SH.600262',
 'SH.600263',
 'SH.600265',
 'SH.600266',
 'SH.600267',
 'SH.600268',
 'SH.600269',
 'SH.600270',
 'SH.600271',
 'SH.600272',
 'SH.600273',
 'SH.600275',
 'SH.600276',
 'SH.600277',
 'SH.600278',
 'SH.600279',
 'SH.600280',
 'SH.600281',
 'SH.600282',
 'SH.600283',
 'SH.600284',
 'SH.600285',
 'SH.600286',
 'SH.600287',
 'SH.600288',
 'SH.600289',
 'SH.600290',
 'SH.600291',
 'SH.600292',
 'SH.600293',
 'SH.600295',
 'SH.600296',
 'SH.600297',
 'SH.600298',
 'SH.600299',
 'SH.600300',
 'SH.600301',
 'SH.600302',
 'SH.600303',
 'SH.600305',
 'SH.600306',
 'SH.600307',
 'SH.600308',
 'SH.600309',
 'SH.600310',
 'SH.600311',
 'SH.600312',
 'SH.600313',
 'SH.600315',
 'SH.600316',
 'SH.600317',
 'SH.600318',
 'SH.600319',
 'SH.600320',
 'SH.600321',
 'SH.600322',
 'SH.600323',
 'SH.600325',
 'SH.600326',
 'SH.600327',
 'SH.600328',
 'SH.600329',
 'SH.600330',
 'SH.600331',
 'SH.600332',
 'SH.600333',
 'SH.600335',
 'SH.600336',
 'SH.600337',
 'SH.600338',
 'SH.600339',
 'SH.600340',
 'SH.600343',
 'SH.600345',
 'SH.600346',
 'SH.600348',
 'SH.600350',
 'SH.600351',
 'SH.600352',
 'SH.600353',
 'SH.600354',
 'SH.600355',
 'SH.600356',
 'SH.600357',
 'SH.600358',
 'SH.600359',
 'SH.600360',
 'SH.600361',
 'SH.600362',
 'SH.600363',
 'SH.600365',
 'SH.600366',
 'SH.600367',
 'SH.600368',
 'SH.600369',
 'SH.600370',
 'SH.600371',
 'SH.600372',
 'SH.600373',
 'SH.600375',
 'SH.600376',
 'SH.600377',
 'SH.600378',
 'SH.600379',
 'SH.600380',
 'SH.600381',
 'SH.600382',
 'SH.600383',
 'SH.600385',
 'SH.600386',
 'SH.600387',
 'SH.600388',
 'SH.600389',
 'SH.600390',
 'SH.600391',
 'SH.600392',
 'SH.600393',
 'SH.600395',
 'SH.600396',
 'SH.600397',
 'SH.600398',
 'SH.600399',
 'SH.600400',
 'SH.600401',
 'SH.600403',
 'SH.600405',
 'SH.600406',
 'SH.600408',
 'SH.600409',
 'SH.600410',
 'SH.600415',
 'SH.600416',
 'SH.600418',
 'SH.600419',
 'SH.600420',
 'SH.600421',
 'SH.600422',
 'SH.600423',
 'SH.600425',
 'SH.600426',
 'SH.600428',
 'SH.600429',
 'SH.600432',
 'SH.600433',
 'SH.600435',
 'SH.600436',
 'SH.600438',
 'SH.600439',
 'SH.600444',
 'SH.600446',
 'SH.600448',
 'SH.600449',
 'SH.600452',
 'SH.600455',
 'SH.600456',
 'SH.600458',
 'SH.600459',
 'SH.600460',
 'SH.600461',
 'SH.600462',
 'SH.600463',
 'SH.600466',
 'SH.600467',
 'SH.600468',
 'SH.600469',
 'SH.600470',
 'SH.600475',
 'SH.600476',
 'SH.600477',
 'SH.600478',
 'SH.600479',
 'SH.600480',
 'SH.600481',
 'SH.600482',
 'SH.600483',
 'SH.600485',
 'SH.600486',
 'SH.600487',
 'SH.600488',
 'SH.600489',
 'SH.600490',
 'SH.600491',
 'SH.600493',
 'SH.600495',
 'SH.600496',
 'SH.600497',
 'SH.600498',
 'SH.600499',
 'SH.600500',
 'SH.600501',
 'SH.600502',
 'SH.600503',
 'SH.600505',
 'SH.600506',
 'SH.600507',
 'SH.600508',
 'SH.600509',
 'SH.600510',
 'SH.600511',
 'SH.600512',
 'SH.600513',
 'SH.600515',
 'SH.600516',
 'SH.600517',
 'SH.600518',
 'SH.600519',
 'SH.600520',
 'SH.600521',
 'SH.600522',
 'SH.600523',
 'SH.600525',
 'SH.600526',
 'SH.600527',
 'SH.600528',
 'SH.600529',
 'SH.600530',
 'SH.600531',
 'SH.600532',
 'SH.600533',
 'SH.600535',
 'SH.600536',
 'SH.600537',
 'SH.600538',
 'SH.600539',
 'SH.600540',
 'SH.600543',
 'SH.600545',
 'SH.600546',
 'SH.600547',
 'SH.600548',
 'SH.600549',
 'SH.600550',
 'SH.600551',
 'SH.600552',
 'SH.600553',
 'SH.600555',
 'SH.600556',
 'SH.600557',
 'SH.600558',
 'SH.600559',
 'SH.600560',
 'SH.600561',
 'SH.600562',
 'SH.600563',
 'SH.600565',
 'SH.600566',
 'SH.600567',
 'SH.600568',
 'SH.600569',
 'SH.600570',
 'SH.600571',
 'SH.600572',
 'SH.600573',
 'SH.600575',
 'SH.600576',
 'SH.600577',
 'SH.600578',
 'SH.600579',
 'SH.600580',
 'SH.600581',
 'SH.600582',
 'SH.600583',
 'SH.600584',
 'SH.600585',
 'SH.600586',
 'SH.600587',
 'SH.600588',
 'SH.600589',
 'SH.600590',
 'SH.600591',
 'SH.600592',
 'SH.600593',
 'SH.600594',
 'SH.600595',
 'SH.600596',
 'SH.600597',
 'SH.600598',
 'SH.600599',
 'SH.600600',
 'SH.600601',
 'SH.600602',
 'SH.600603',
 'SH.600604',
 'SH.600605',
 'SH.600606',
 'SH.600607',
 'SH.600608',
 'SH.600609',
 'SH.600610',
 'SH.600611',
 'SH.600612',
 'SH.600613',
 'SH.600614',
 'SH.600615',
 'SH.600616',
 'SH.600617',
 'SH.600618',
 'SH.600619',
 'SH.600620',
 'SH.600621',
 'SH.600622',
 'SH.600623',
 'SH.600624',
 'SH.600626',
 'SH.600627',
 'SH.600628',
 'SH.600629',
 'SH.600630',
 'SH.600631',
 'SH.600633',
 'SH.600634',
 'SH.600635',
 'SH.600636',
 'SH.600637',
 'SH.600638',
 'SH.600639',
 'SH.600640',
 'SH.600641',
 'SH.600642',
 'SH.600643',
 'SH.600644',
 'SH.600645',
 'SH.600647',
 'SH.600648',
 'SH.600649',
 'SH.600650',
 'SH.600651',
 'SH.600652',
 'SH.600653',
 'SH.600654',
 'SH.600655',
 'SH.600656',
 'SH.600657',
 'SH.600658',
 'SH.600659',
 'SH.600660',
 'SH.600661',
 'SH.600662',
 'SH.600663',
 'SH.600664',
 'SH.600665',
 'SH.600666',
 'SH.600667',
 'SH.600668',
 'SH.600671',
 'SH.600672',
 'SH.600673',
 'SH.600674',
 'SH.600675',
 'SH.600676',
 'SH.600677',
 'SH.600678',
 'SH.600679',
 'SH.600680',
 'SH.600681',
 'SH.600682',
 'SH.600683',
 'SH.600684',
 'SH.600685',
 'SH.600686',
 'SH.600687',
 'SH.600688',
 'SH.600689',
 'SH.600690',
 'SH.600691',
 'SH.600692',
 'SH.600693',
 'SH.600694',
 'SH.600695',
 'SH.600696',
 'SH.600697',
 'SH.600698',
 'SH.600699',
 'SH.600700',
 'SH.600701',
 'SH.600702',
 'SH.600703',
 'SH.600704',
 'SH.600705',
 'SH.600706',
 'SH.600707',
 'SH.600708',
 'SH.600710',
 'SH.600711',
 'SH.600712',
 'SH.600713',
 'SH.600714',
 'SH.600715',
 'SH.600716',
 'SH.600717',
 'SH.600718',
 'SH.600719',
 'SH.600720',
 'SH.600721',
 'SH.600722',
 'SH.600723',
 'SH.600724',
 'SH.600725',
 'SH.600726',
 'SH.600727',
 'SH.600728',
 'SH.600729',
 'SH.600730',
 'SH.600731',
 'SH.600732',
 'SH.600733',
 'SH.600734',
 'SH.600735',
 'SH.600736',
 'SH.600737',
 'SH.600738',
 'SH.600739',
 'SH.600740',
 'SH.600741',
 'SH.600742',
 'SH.600743',
 'SH.600744',
 'SH.600745',
 'SH.600746',
 'SH.600747',
 'SH.600748',
 'SH.600749',
 'SH.600750',
 'SH.600751',
 'SH.600752',
 'SH.600753',
 'SH.600754',
 'SH.600755',
 'SH.600756',
 'SH.600757',
 'SH.600758',
 'SH.600759',
 'SH.600760',
 'SH.600761',
 'SH.600762',
 'SH.600763',
 'SH.600764',
 'SH.600765',
 'SH.600766',
 'SH.600767',
 'SH.600768',
 'SH.600769',
 'SH.600770',
 'SH.600771',
 'SH.600772',
 'SH.600773',
 'SH.600774',
 'SH.600775',
 'SH.600776',
 'SH.600777',
 'SH.600778',
 'SH.600779',
 'SH.600780',
 'SH.600781',
 'SH.600782',
 'SH.600783',
 'SH.600784',
 'SH.600785',
 'SH.600786',
 'SH.600787',
 'SH.600788',
 'SH.600789',
 'SH.600790',
 'SH.600791',
 'SH.600792',
 'SH.600793',
 'SH.600794',
 'SH.600795',
 'SH.600796',
 'SH.600797',
 'SH.600798',
 'SH.600799',
 'SH.600800',
 'SH.600801',
 'SH.600802',
 'SH.600803',
 'SH.600804',
 'SH.600805',
 'SH.600806',
 'SH.600807',
 'SH.600808',
 'SH.600809',
 'SH.600810',
 'SH.600811',
 'SH.600812',
 'SH.600814',
 'SH.600815',
 'SH.600816',
 'SH.600817',
 'SH.600818',
 'SH.600819',
 'SH.600820',
 'SH.600821',
 'SH.600822',
 'SH.600823',
 'SH.600824',
 'SH.600825',
 'SH.600826',
 'SH.600827',
 'SH.600828',
 'SH.600829',
 'SH.600830',
 'SH.600831',
 'SH.600832',
 'SH.600833',
 'SH.600834',
 'SH.600835',
 'SH.600836',
 'SH.600837',
 'SH.600838',
 'SH.600839',
 'SH.600840',
 'SH.600841',
 'SH.600842',
 'SH.600843',
 'SH.600844',
 'SH.600845',
 'SH.600846',
 'SH.600847',
 'SH.600848',
 'SH.600849',
 'SH.600850',
 'SH.600851',
 'SH.600852',
 'SH.600853',
 'SH.600854',
 'SH.600855',
 'SH.600856',
 'SH.600857',
 'SH.600858',
 'SH.600859',
 'SH.600860',
 'SH.600861',
 'SH.600862',
 'SH.600863',
 'SH.600864',
 'SH.600865',
 'SH.600866',
 'SH.600867',
 'SH.600868',
 'SH.600869',
 'SH.600870',
 'SH.600871',
 'SH.600872',
 'SH.600873',
 'SH.600874',
 'SH.600875',
 'SH.600876',
 'SH.600877',
 'SH.600879',
 'SH.600880',
 'SH.600881',
 'SH.600882',
 'SH.600883',
 'SH.600884',
 'SH.600885',
 'SH.600886',
 'SH.600887',
 'SH.600888',
 'SH.600889',
 'SH.600890',
 'SH.600891',
 'SH.600892',
 'SH.600893',
 'SH.600894',
 'SH.600895',
 'SH.600896',
 'SH.600897',
 'SH.600898',
 'SH.600899',
 'SH.600900',
 'SH.600960',
 'SH.600961',
 'SH.600962',
 'SH.600963',
 'SH.600965',
 'SH.600966',
 'SH.600967',
 'SH.600969',
 'SH.600971',
 'SH.600973',
 'SH.600975',
 'SH.600976',
 'SH.600978',
 'SH.600979',
 'SH.600980',
 'SH.600981',
 'SH.600982',
 'SH.600983',
 'SH.600984',
 'SH.600985',
 'SH.600986',
 'SH.600987',
 'SH.600988',
 'SH.600990',
 'SH.600991',
 'SH.600992',
 'SH.600993',
 'SH.600995',
 'SH.600997',
 'SZ.000001',
 'SZ.000002',
 'SZ.000004',
 'SZ.000005',
 'SZ.000006',
 'SZ.000007',
 'SZ.000008',
 'SZ.000009',
 'SZ.000010',
 'SZ.000011',
 'SZ.000012',
 'SZ.000014',
 'SZ.000016',
 'SZ.000017',
 'SZ.000018',
 'SZ.000019',
 'SZ.000020',
 'SZ.000021',
 'SZ.000022',
 'SZ.000023',
 'SZ.000024',
 'SZ.000025',
 'SZ.000026',
 'SZ.000027',
 'SZ.000028',
 'SZ.000029',
 'SZ.000030',
 'SZ.000031',
 'SZ.000032',
 'SZ.000033',
 'SZ.000034',
 'SZ.000035',
 'SZ.000036',
 'SZ.000037',
 'SZ.000038',
 'SZ.000039',
 'SZ.000040',
 'SZ.000042',
 'SZ.000043',
 'SZ.000045',
 'SZ.000046',
 'SZ.000048',
 'SZ.000049',
 'SZ.000050',
 'SZ.000055',
 'SZ.000056',
 'SZ.000058',
 'SZ.000059',
 'SZ.000060',
 'SZ.000061',
 'SZ.000062',
 'SZ.000063',
 'SZ.000065',
 'SZ.000066',
 'SZ.000068',
 'SZ.000069',
 'SZ.000070',
 'SZ.000078',
 'SZ.000088',
 'SZ.000089',
 'SZ.000090',
 'SZ.000096',
 'SZ.000099',
 'SZ.000100',
 'SZ.000150',
 'SZ.000151',
 'SZ.000153',
 'SZ.000155',
 'SZ.000156',
 'SZ.000157',
 'SZ.000158',
 'SZ.000159',
 'SZ.000301',
 'SZ.000400',
 'SZ.000401',
 'SZ.000402',
 'SZ.000403',
 'SZ.000404',
 'SZ.000406',
 'SZ.000407',
 'SZ.000408',
 'SZ.000409',
 'SZ.000410',
 'SZ.000411',
 'SZ.000413',
 'SZ.000415',
 'SZ.000416',
 'SZ.000417',
 'SZ.000418',
 'SZ.000419',
 'SZ.000420',
 'SZ.000421',
 'SZ.000422',
 'SZ.000423',
 'SZ.000425',
 'SZ.000426',
 'SZ.000428',
 'SZ.000429',
 'SZ.000430',
 'SZ.000488',
 'SZ.000498',
 'SZ.000501',
 'SZ.000502',
 'SZ.000503',
 'SZ.000504',
 'SZ.000505',
 'SZ.000506',
 'SZ.000507',
 'SZ.000509',
 'SZ.000510',
 'SZ.000511',
 'SZ.000513',
 'SZ.000514',
 'SZ.000515',
 'SZ.000516',
 'SZ.000517',
 'SZ.000518',
 'SZ.000519',
 'SZ.000520',
 'SZ.000521',
 'SZ.000522',
 'SZ.000523',
 'SZ.000524',
 'SZ.000525',
 'SZ.000526',
 'SZ.000527',
 'SZ.000528',
 'SZ.000529',
 'SZ.000530',
 'SZ.000531',
 'SZ.000532',
 'SZ.000533',
 'SZ.000534',
 'SZ.000535',
 'SZ.000536',
 'SZ.000537',
 'SZ.000538',
 'SZ.000539',
 'SZ.000540',
 'SZ.000541',
 'SZ.000543',
 'SZ.000544',
 'SZ.000545',
 'SZ.000546',
 'SZ.000547',
 'SZ.000548',
 'SZ.000549',
 'SZ.000550',
 'SZ.000551',
 'SZ.000552',
 'SZ.000553',
 'SZ.000554',
 'SZ.000555',
 'SZ.000557',
 'SZ.000558',
 'SZ.000559',
 'SZ.000560',
 'SZ.000561',
 'SZ.000562',
 'SZ.000563',
 ...]

In [15]:
index = file.codetable.symbols.index("SH.600000")
file.ci_type.item_data(file.codetable.data[index])

IndexError: index 13 is out of bounds for axis 0 with size 0

In [7]:
import pandas as pd
codetable_pd = pd.DataFrame(file.ci_type.items_data(file.codetable.data))
codetable_pd["sec_name"] = codetable_pd["sec_name"].map(lambda x: x.decode("gbk"))
codetable_pd

,sec_type,sec_name,date,high_limited,low_limited,multiplier,margin_ratio,price_tick,capital,cap_change_date,trade_date_in,trade_date_out,is_halt,margin_unit,margin_ratio_param1,margin_ratio_param2,sec_name_ext
0,3,深证100ETF沽3月2200,20250121,1741,1,0,0,1,0,0,20240725,20250326,0,16050000,120000,70000,b'\xc9\xee\xd6\xa4100ETF\xb9\xc13\xd4\xc22200'
1,3,创业板ETF购3月1650,20250121,8342,94,0,0,1,0,0,20240725,20250326,0,66924000,120000,70000,b'\xb4\xb4\xd2\xb5\xb0\xe5ETF\xb9\xba3\xd4\xc2...
2,3,沪深300ETF沽3月3354A,20250121,2753,1,0,0,1,0,0,20240725,20250326,0,24407900,120000,70000,b'\xbb\xa6\xc9\xee300ETF\xb9\xc13\xd4\xc23354A'
3,3,中证500ETF沽3月2179A,20250121,2814,1,0,0,1,0,0,20240725,20250326,0,72983400,120000,70000,b'\xd6\xd0\xd6\xa4500ETF\xb9\xc13\xd4\xc22179A'
4,3,沪深300ETF沽3月2959A,20250121,1925,1,0,0,1,0,0,20240909,20250326,0,21219800,120000,70000,b'\xbb\xa6\xc9\xee300ETF\xb9\xc13\xd4\xc22959A'
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60409,5,动力定02,0,999999999,10,0,0,10,0,0,20210309,0,0,0,0,0,b'\xb6\xaf\xc1\xa6\xb6\xa802'
60410,5,铜陵定02,20250121,0,0,0,0,0,0,0,20240306,0,0,0,0,0,b'\xcd\xad\xc1\xea\xb6\xa802'
60411,0,,0,0,0,0,0,0,0,0,20250102,20250418,0,0,0,0,b''
60412,0,,0,0,0,0,0,0,0,0,20241101,20250218,0,0,0,0,b''
60413,0,,0,0,0,0,0,0,0,0,20241202,20250319,0,0,0,0,b''

In [8]:
file.codetable.data

array([2940272635968, 2940272636114, 2940272636260, ..., 2940281455974,
       2940281456120, 2940281456266], shape=(60414,), dtype=uint64)

#### 读取快照数据

In [6]:
#读取SZ.300打头的股票快照数据
task = file.open_read_task(symbols=["SZ.300*"], types=["SecurityTick"])

In [7]:
items = task.read()

In [8]:
#items 为读取出的数据，其中data字段为具体数据的地址
# 需要通过对应的数据类型定义来解析数据
items

array([(b'SZ.300003', 23075, 20220506, 1651798222227, 59, 0, 2098824818800),
       (b'SZ.300004', 23077, 20220506, 1651798222227, 61, 0, 2098824819076),
       (b'SZ.300006', 23078, 20220506, 1651798222227, 62, 0, 2098824819352),
       ...,
       (b'SZ.300978', 24236, 20220506, 1651823945641, 15, 0, 2099802949552),
       (b'SZ.300982', 24239, 20220506, 1651823945641, 18, 0, 2099802949828),
       (b'SZ.300999', 24240, 20220506, 1651823945641, 21, 0, 2099802950104)],
      dtype=[('symbol', 'S24'), ('index', '<i4'), ('trading_day', '<i4'), ('local_time', '<i8'), ('time_point_seq_no', '<i4'), ('type_id', '<i4'), ('data', '<u8')])

In [9]:
type_id = items[0]["type_id"]
file.data_types[type_id].name
#items[0]的type_id字段对应的data_type是SecurityTick

'SecurityTick'

In [10]:
data = file.data_types[type_id].items_data(items["data"])
data

array([( 85021000, 0, 173900,      0,      0,      0, 173900, [     0,      0,      0,      0,      0,      0,      0,      0,      0,      0], [    0,     0,     0,     0,     0,     0,     0,     0,     0,     0], [     0,      0,      0,      0,      0,      0,      0,      0,      0,      0], [     0,      0,      0,      0,      0,      0,      0,      0,      0,      0],     0,        0,         0,       0,       0,      0,      0, 0, 0, 208700, 139100, b'', 182500, 0,          0, b'S0      ', 0),
       ( 85021000, 0,  54700,      0,      0,      0,  54700, [     0,      0,      0,      0,      0,      0,      0,      0,      0,      0], [    0,     0,     0,     0,     0,     0,     0,     0,     0,     0], [     0,      0,      0,      0,      0,      0,      0,      0,      0,      0], [     0,      0,      0,      0,      0,      0,      0,      0,      0,      0],     0,        0,         0,       0,       0,      0,      0, 0, 0,  65600,  43800, b'',      0, 0,          0, b'S0      ', 0),
       ( 85021000, 0,  40600,      0,      0,      0,  40600, [     0,      0,      0,      0,      0,      0,      0,      0,      0,      0], [    0,     0,     0,     0,     0,     0,     0,     0,     0,     0], [     0,      0,      0,      0,      0,      0,      0,      0,      0,      0], [     0,      0,      0,      0,      0,      0,      0,      0,      0,      0],     0,        0,         0,       0,       0,      0,      0, 0, 0,  48700,  32500, b'',      0, 0,          0, b'S0      ', 0),
       ...,
       (155903000, 0, 108600, 105100, 110000, 105100, 110000, [110000, 110100, 110300, 110400, 110500, 110600, 110800, 110900, 111000, 111100], [ 7200,  1700,  2100,   400,  6000,  2200,  3800,  1000,  2700,   200], [109000, 108900, 108800, 108700, 108600, 108500, 108200, 108100, 108000, 107900], [  3700,    100,    400,  34400,   1000,   1000,    400,   2200,  19200,   2400],  3718,  1778445,  19219027,  187400,  222700, 105900, 123100, 0, 0, 130300,  86900, b'', 401300, 0,       1400, b'E0      ', 0),
       (155903000, 0, 395200, 382200, 392500, 378800, 385400, [385400, 386000, 386200, 386300, 386400, 386800, 387400, 387500, 387700, 387900], [ 7900,  1500,   600,   300,  1000,   600,  1400,  2500,  1900,   500], [385300, 385200, 385000, 384900, 384800, 384700, 384500, 384100, 384000, 383100], [  1500,   2500,   6200,    400,   1800,   2400,   3300,   1600,    700,    600],  4921,  1247682,  48067026,   92300,  137500, 378500, 427100, 0, 0, 474200, 316200, b'', 179600, 0,        400, b'E0      ', 0),
       (155903000, 0, 441700, 430000, 441000, 427700, 434500, [434500, 434600, 434700, 434800, 434900, 435000, 435100, 435200, 435300, 435400], [20320, 16300,  3900,  1608,  3600,  6700,  1600,  1000,  1400,   700], [434400, 434300, 434200, 434100, 434000, 433900, 433800, 433700, 433600, 433500], [129600,  16600,  20800,  15300,  65100,   2700,   2100,    100,   4400,   4200], 34124, 12364069, 538834689, 1562500, 1556541, 416700, 471600, 0, 0, 530000, 353400, b'', 570100, 0, -171798792, b'E0      ', 0)],
      dtype=[('time', '<i4'), ('status', '<i4'), ('pre_close', '<u4'), ('open', '<u4'), ('high', '<u4'), ('low', '<u4'), ('match', '<u4'), ('ask_price', '<u4', (10,)), ('ask_vol', '<u4', (10,)), ('bid_price', '<u4', (10,)), ('bid_vol', '<u4', (10,)), ('num_trades', '<u4'), ('volume', '<i8'), ('turnover', '<i8'), ('total_bid_vol', '<i8'), ('total_ask_vol', '<i8'), ('weighted_avg_bid_price', '<u4'), ('weighted_avg_ask_price', '<u4'), ('iopv', '<i4'), ('yield_to_maturity', '<i4'), ('high_limited', '<u4'), ('low_limited', '<u4'), ('prefix', 'S4'), ('syl1', '<i4'), ('syl2', '<i4'), ('sd2', '<i4'), ('trading_phase_code', 'S8'), ('pre_iopv', '<i4')])

In [11]:
#把data中的字段分别插入dataframe中
#因为dataframe不支持某一个字段是数组类型，所以需要将该字段拆解成多个单独的字段（比如bid_price包含10档数据）
df = pd.DataFrame()
data_type = file.data_types[items[0]["type_id"]]
for name in data_type.dtype.fields:
    field_type = data.dtype.fields[name][0]
    if 0 == field_type.ndim:
        df[name] = data[name]
    elif 1 == field_type.ndim:
        for idx in range(field_type.shape[0]):
            df[name + '.' + str(idx)] = data[name][:, idx]

df['symbol'] = items['symbol']
df['date'] = items['trading_day']
df

,time,status,pre_close,open,high,low,match,ask_price.0,ask_price.1,ask_price.2,...,high_limited,low_limited,prefix,syl1,syl2,sd2,trading_phase_code,pre_iopv,symbol,date
0,85021000,0,173900,0,0,0,173900,0,0,0,...,208700,139100,b'',182500,0,0,b'S0 ',0,b'SZ.300003',20220506
1,85021000,0,54700,0,0,0,54700,0,0,0,...,65600,43800,b'',0,0,0,b'S0 ',0,b'SZ.300004',20220506
2,85021000,0,40600,0,0,0,40600,0,0,0,...,48700,32500,b'',0,0,0,b'S0 ',0,b'SZ.300006',20220506
3,85021000,0,148800,0,0,0,148800,0,0,0,...,178600,119000,b'',183400,0,0,b'S0 ',0,b'SZ.300007',20220506
4,85021000,0,60100,0,0,0,60100,0,0,0,...,72100,48100,b'',0,0,0,b'S0 ',0,b'SZ.300013',20220506
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3543950,155903000,0,169700,163000,170100,162600,167500,167600,167700,167800,...,203600,135800,b'',389300,0,-171798792,b'E0 ',0,b'SZ.300967',20220506
3543951,155903000,0,333100,326700,335000,322500,327400,327800,328000,328200,...,399700,266500,b'',187900,0,-171798892,b'E0 ',0,b'SZ.300977',20220506
3543952,155903000,0,108600,105100,110000,105100,110000,110000,110100,110300,...,130300,86900,b'',401300,0,1400,b'E0 ',0,b'SZ.300978',20220506
3543953,155903000,0,395200,382200,392500,378800,385400,385400,386000,386200,...,474200,316200,b'',179600,0,400,b'E0 ',0,b'SZ.300982',20220506
3543954,155903000,0,441700,430000,441000,427700,434500,434500,434600,434700,...,530000,353400,b'',570100,0,-171798792,b'E0 ',0,b'SZ.300999',20220506

In [12]:
#将上述过程封装后可以调用read_data
def read_data(f, symbols, data_type, begin=None, end=None):
    if (begin is None) and (end is None):
        task = f.open_read_task(symbols=symbols, types=[data_type])
    elif begin is None:
        task = f.open_read_task(end_time=end, symbols=symbols, types=[data_type])
    elif end is None:
        task = f.open_read_task(begin_time=begin, symbols=symbols, types=[data_type])
    else:
        task = f.open_read_task(begin_time=begin, end_time=end, symbols=symbols, types=[data_type])
    items = task.read()
    data_type = f.data_types[items['type_id'][0]]
    data = data_type.items_data(items['data'])
    df = pd.DataFrame()
    for name in data_type.dtype.fields:
        field_type = data.dtype.fields[name][0]
        if 0 == field_type.ndim:
            df[name] = data[name]
        elif 1 == field_type.ndim:
            for idx in range(field_type.shape[0]):
                df[name + '.' + str(idx)] = data[name][:, idx]
    task.close()
    df['symbol'] = items['symbol']
    df['date'] = items['trading_day']
    return df

data = read_data(file, ["SZ.300*"], "SecurityTick")

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3543955 entries, 0 to 3543954
Data columns (total 66 columns):
 #   Column                  Dtype
---  ------                  -----
 0   time                    int32
 1   status                  int32
 2   pre_close               uint32
 3   open                    uint32
 4   high                    uint32
 5   low                     uint32
 6   match                   uint32
 7   ask_price.0             uint32
 8   ask_price.1             uint32
 9   ask_price.2             uint32
 10  ask_price.3             uint32
 11  ask_price.4             uint32
 12  ask_price.5             uint32
 13  ask_price.6             uint32
 14  ask_price.7             uint32
 15  ask_price.8             uint32
 16  ask_price.9             uint32
 17  ask_vol.0               uint32
 18  ask_vol.1               uint32
 19  ask_vol.2               uint32
 20  ask_vol.3               uint32
 21  ask_vol.4               uint32
 22  ask_vol.5               uint32
 23  ask_vol.6               uint32
 24  ask_vol.7               uint32
 25  ask_vol.8               uint32
 26  ask_vol.9               uint32
 27  bid_price.0             uint32
 28  bid_price.1             uint32
 29  bid_price.2             uint32
 30  bid_price.3             uint32
 31  bid_price.4             uint32
 32  bid_price.5             uint32
 33  bid_price.6             uint32
 34  bid_price.7             uint32
 35  bid_price.8             uint32
 36  bid_price.9             uint32
 37  bid_vol.0               uint32
 38  bid_vol.1               uint32
 39  bid_vol.2               uint32
 40  bid_vol.3               uint32
 41  bid_vol.4               uint32
 42  bid_vol.5               uint32
 43  bid_vol.6               uint32
 44  bid_vol.7               uint32
 45  bid_vol.8               uint32
 46  bid_vol.9               uint32
 47  num_trades              uint32
 48  volume                  int64
 49  turnover                int64
 50  total_bid_vol           int64
 51  total_ask_vol           int64
 52  weighted_avg_bid_price  uint32
 53  weighted_avg_ask_price  uint32
 54  iopv                    int32
 55  yield_to_maturity       int32
 56  high_limited            uint32
 57  low_limited             uint32
 58  prefix                  |S4
 59  syl1                    int32
 60  syl2                    int32
 61  sd2                     int32
 62  trading_phase_code      |S8
 63  pre_iopv                int32
 64  symbol                  |S24
 65  date                    int32
dtypes: bytes192(1), bytes32(1), bytes64(1), int32(9), int64(4), uint32(50)
memory usage: 1.0 GB

In [14]:
data.head()

,time,status,pre_close,open,high,low,match,ask_price.0,ask_price.1,ask_price.2,...,high_limited,low_limited,prefix,syl1,syl2,sd2,trading_phase_code,pre_iopv,symbol,date
0,85021000,0,173900,0,0,0,173900,0,0,0,...,208700,139100,b'',182500,0,0,b'S0 ',0,b'SZ.300003',20220506
1,85021000,0,54700,0,0,0,54700,0,0,0,...,65600,43800,b'',0,0,0,b'S0 ',0,b'SZ.300004',20220506
2,85021000,0,40600,0,0,0,40600,0,0,0,...,48700,32500,b'',0,0,0,b'S0 ',0,b'SZ.300006',20220506
3,85021000,0,148800,0,0,0,148800,0,0,0,...,178600,119000,b'',183400,0,0,b'S0 ',0,b'SZ.300007',20220506
4,85021000,0,60100,0,0,0,60100,0,0,0,...,72100,48100,b'',0,0,0,b'S0 ',0,b'SZ.300013',20220506

#### 读取逐笔成交数据

In [15]:
['SecurityTick',
 'IndexTick',
 'FuturesTick',
 'OptionsTick',
 'SHStepTrade',
 'SZStepTrade',
 'SZStepOrder',
 'OrderQueueItem',
 'SZOptionsTick',
 'SHStepOrder',
 'FPSHStepTrade']

['SecurityTick',
 'IndexTick',
 'FuturesTick',
 'OptionsTick',
 'SHStepTrade',
 'SZStepTrade',
 'SZStepOrder',
 'OrderQueueItem',
 'SZOptionsTick',
 'SHStepOrder',
 'FPSHStepTrade']

In [16]:
#将上述过程封装后可以调用read_data
data = read_data(file, ["SZ.300*"], "SZStepTrade")
data.head()

,channel_no,appl_seq_num,md_stream_id,bid_appl_seq_num,offer_appl_seq_num,security_id,security_id_source,last_px,last_qty,exec_type,transact_time,symbol,date
0,2011,538,b'011',0,43,b'300481 ',b'102 ',0,2000,52,91500030,b'SZ.300481',20220506
1,2011,1153,b'011',1152,0,b'300446 ',b'102 ',0,100,52,91500030,b'SZ.300446',20220506
2,2014,1795,b'011',1794,0,b'300857 ',b'102 ',0,1300,52,91500030,b'SZ.300857',20220506
3,2012,3682,b'011',0,3677,b'300438 ',b'102 ',0,5200,52,91500030,b'SZ.300438',20220506
4,2012,3697,b'011',0,3696,b'300438 ',b'102 ',0,5200,52,91500030,b'SZ.300438',20220506

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18719104 entries, 0 to 18719103
Data columns (total 13 columns):
 #   Column              Dtype
---  ------              -----
 0   channel_no          uint16
 1   appl_seq_num        int64
 2   md_stream_id        |S3
 3   bid_appl_seq_num    int64
 4   offer_appl_seq_num  int64
 5   security_id         |S8
 6   security_id_source  |S4
 7   last_px             int64
 8   last_qty            int64
 9   exec_type           int8
 10  transact_time       int64
 11  symbol              |S24
 12  date                int32
dtypes: bytes192(1), bytes24(1), bytes32(1), bytes64(1), int32(1), int64(6), int8(1), uint16(1)
memory usage: 1.6 GB

In [18]:
file.close()

### 获取k线数据及复权数据
#### 获取不复权k线数据

In [19]:
# 该函数可以获取不复权的k线
def load_min_bar_from_hdb(symbols,
                          db_path,
                          start,
                          end):
    start_date = int(start.strftime("%Y%m%d"))
    end_date = int(end.strftime("%Y%m%d"))
    db = hdb.DB(db_path)
    total_dates = db.get_trading_days(start_date, end_date)
    load_year = None
    load_years = []
    for cur_date in total_dates:
        cur_year = cur_date // 10000
        if cur_year != load_year:
            load_year = cur_year
            load_years.append(str(cur_year))
    ret = []
    for cur_year in load_years:
        file_name = "%s_%s" % ("bar/day_bar", cur_year)
        file = db.open_file(file_name)
        data = read_data(file, symbols, "SecurityKdata", start, end)
        ret.append(data)
        file.close()
    kline_data = pd.concat(ret)
    kline_data["symbol"] = kline_data["symbol"].str.decode("utf8")
#    kline_data["date"] = pd.to_datetime(kline_data["date"], format="%Y%m%d")
    return kline_data

In [21]:
import datetime
start = datetime.date(2022,11,1)
end = datetime.date(2023,1,31)
symbols = ["SZ.123119","SH.600085"]
db_path = "Z:/hdb_data"
kline_data = load_min_bar_from_hdb(symbols, db_path, start, end)
kline_data

,date,time,pre_close,open,high,low,close,volume,turnover,open_interest,pre_settle_price,settle_price,symbol
0,20221101,150000,1255000,1248100,1291790,1248100,1283460,654877,83368647,0,0,0,SZ.123119
1,20221101,150000,487500,476000,481800,462800,473000,22655583,1065165972,0,0,0,SH.600085
2,20221102,150000,1283460,1285400,1321780,1283450,1318980,2387949,312538036,0,0,0,SZ.123119
3,20221102,150000,473000,482500,515100,474500,495800,25116193,1241642059,0,0,0,SH.600085
4,20221103,150000,1318980,1307340,1325260,1300000,1309380,994107,130432348,0,0,0,SZ.123119
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25,20230119,150000,459300,459400,470800,458000,466500,7573774,352756964,0,0,0,SH.600085
26,20230120,150000,1316000,1314180,1330000,1307250,1318590,320039,42281249,0,0,0,SZ.123119
27,20230120,150000,466500,466300,478100,466000,469800,9153584,432152230,0,0,0,SH.600085
28,20230130,150000,1318590,1319400,1345000,1319400,1329990,577822,76966278,0,0,0,SZ.123119
29,20230130,150000,469800,471900,490000,468000,483700,13724034,660034446,0,0,0,SH.600085

#### 获取复权因子
load_adj_factor(data_base_path, symbols, begin_date, end_date, fq, is_from_initial=False) 
  
方法描述：
    
    该方法可以获取指定股票列表，日期在闭区间[begin_date, end_date]内，每天每支标的的复权因子。复权因子乘以不复权价即可得对应的复权价。
    
参数描述：

    data_base_path：HDB目录
    symbols：股票代码列表
    begin_date：开始日期，格式：yyyymmdd，例如20220101
    end_date：结束日期，格式同上
    fq：复权方式，前复权填“pre”，后复权填“post”。
    is_from_initial：后复权时，复权价是否从上市首日开始计算，默认值为False
    
返回：每只标的，在闭区间[begin_date, end_date]内的所有复权因子

In [22]:
def load_adj_factor(data_base_path, symbols, begin_date, end_date, fq, is_from_initial=False):
    db = hdb.DB(data_base_path)
    total_dates = db.get_trading_days(begin_date, end_date)
    load_year = None
    load_years = []
    is_from_initial
    for cur_date in total_dates:
        cur_year = cur_date // 10000
        if cur_year != load_year:
            load_year = cur_year
            load_years.append(cur_year)
    adj_factors = dict()
    adj_data = dict()
    for cur_year in load_years:
        file_path = "bar\day_bar_%s" % cur_year
        file = db.open_file(file_path, mode="r")
        for symbol in symbols:
            if is_from_initial:
                index =  file.codetable.symbols.index(symbol)
                codeinfo = file.ci_type.item_data(file.codetable.data[index])
                bdate = codeinfo['date'][0]        
                begin_time = max(datetime.datetime(cur_year,1,1,0),datetime.datetime.strptime(str(bdate),"%Y%m%d"))
                if not(symbol in adj_factors.keys()):
                    adj_factors[symbol] = (codeinfo["capital"] / codeinfo["multiplier"])[0]   
            else:
                begin_time = max(datetime.datetime(cur_year,1,1,0),datetime.datetime.strptime(str(begin_date),"%Y%m%d"))
                if not(symbol in adj_factors.keys()):
                    adj_factors[symbol] = 1
            end_time = min(datetime.datetime(cur_year,12,31,23,59,59),datetime.datetime.strptime(str(end_date),"%Y%m%d"))
            data = file.read([symbol],"SecurityKdata",["date","pre_close","close"],begin_time,end_time)
            data_pd = hdb.util.convert_hdbframe_to_pandasframe(data, ["date","pre_close","close"])
            if symbol in adj_data.keys():
                adj_data[symbol] = pd.concat([adj_data[symbol], data_pd])
            else:
                adj_data[symbol] = data_pd
    qfactor = dict()
    for symbol in symbols:
        daybar = adj_data[symbol]
        if fq == "pre":
            daybar["fq_factor"] = daybar["pre_close"]/daybar["close"]
            close = daybar["close"].iloc[-1]
            daybar["fq_factor"] = daybar["fq_factor"].iloc[::-1].cumprod()[::-1]
            daybar["fq_factor"] = daybar["fq_factor"]*close
            daybar["fq_factor"] = daybar["fq_factor"]/daybar["pre_close"]
        elif fq == "post":
            adj_factor = adj_factors[symbol]
            daybar["fq_factor"] = daybar["close"]/daybar["pre_close"]
            daybar["fq_factor"] = daybar["fq_factor"].cumprod()
            pre_close = daybar["pre_close"].iloc[0]
            daybar["fq_factor"] = daybar["fq_factor"]*pre_close*adj_factor
            daybar["fq_factor"] = daybar["fq_factor"]/daybar["close"]
            daybar = daybar[daybar["date"]>=begin_date]
#        qfactor[symbol] = daybar
        qfactor[symbol] = daybar.groupby("date")["fq_factor"].first().to_dict()
    return qfactor

In [23]:
db_path = "Z:/hdb_data"
symbols = ["SH.600085","SZ.000001"]
begin_date = 20210801
end_date = 20230310
fq = "post"
factor = load_adj_factor(db_path, symbols, begin_date, end_date, fq, is_from_initial=True) 
factor

{'SH.600085': {20210802: 11.430051000000002,
  20210803: 11.430051,
  20210804: 11.430051,
  20210805: 11.430051,
  20210806: 11.430051,
  20210809: 11.430051,
  20210810: 11.430051,
  20210811: 11.430050999999999,
  20210812: 11.520130211033274,
  20210813: 11.520130211033274,
  20210816: 11.520130211033273,
  20210817: 11.52013021103327,
  20210818: 11.52013021103327,
  20210819: 11.520130211033269,
  20210820: 11.520130211033269,
  20210823: 11.520130211033269,
  20210824: 11.52013021103327,
  20210825: 11.520130211033273,
  20210826: 11.520130211033273,
  20210827: 11.520130211033273,
  20210830: 11.520130211033269,
  20210831: 11.52013021103327,
  20210901: 11.520130211033269,
  20210902: 11.520130211033269,
  20210903: 11.520130211033269,
  20210906: 11.520130211033269,
  20210907: 11.520130211033269,
  20210908: 11.520130211033267,
  20210909: 11.520130211033269,
  20210910: 11.520130211033269,
  20210913: 11.520130211033269,
  20210914: 11.520130211033266,
  20210915: 11.520130211033266,
  20210916: 11.520130211033266,
  20210917: 11.520130211033266,
  20210922: 11.520130211033264,
  20210923: 11.520130211033266,
  20210924: 11.520130211033266,
  20210927: 11.520130211033267,
  20210928: 11.520130211033266,
  20210929: 11.520130211033267,
  20210930: 11.520130211033266,
  20211008: 11.520130211033266,
  20211011: 11.520130211033266,
  20211012: 11.520130211033266,
  20211013: 11.520130211033264,
  20211014: 11.520130211033264,
  20211015: 11.520130211033266,
  20211018: 11.520130211033266,
  20211019: 11.520130211033266,
  20211020: 11.520130211033266,
  20211021: 11.520130211033267,
  20211022: 11.520130211033267,
  20211025: 11.520130211033267,
  20211026: 11.520130211033264,
  20211027: 11.520130211033266,
  20211028: 11.520130211033266,
  20211029: 11.520130211033266,
  20211101: 11.520130211033264,
  20211102: 11.520130211033264,
  20211103: 11.520130211033262,
  20211104: 11.520130211033264,
  20211105: 11.520130211033264,
  20211108: 11.520130211033264,
  20211109: 11.520130211033266,
  20211110: 11.520130211033266,
  20211111: 11.520130211033266,
  20211112: 11.520130211033266,
  20211115: 11.520130211033267,
  20211116: 11.520130211033267,
  20211117: 11.520130211033266,
  20211118: 11.520130211033266,
  20211119: 11.520130211033266,
  20211122: 11.520130211033266,
  20211123: 11.520130211033266,
  20211124: 11.520130211033266,
  20211125: 11.520130211033267,
  20211126: 11.520130211033266,
  20211129: 11.520130211033266,
  20211130: 11.520130211033264,
  20211201: 11.520130211033262,
  20211202: 11.520130211033262,
  20211203: 11.520130211033262,
  20211206: 11.52013021103326,
  20211207: 11.52013021103326,
  20211208: 11.52013021103326,
  20211209: 11.52013021103326,
  20211210: 11.52013021103326,
  20211213: 11.520130211033262,
  20211214: 11.52013021103326,
  20211215: 11.520130211033262,
  20211216: 11.52013021103326,
  20211217: 11.52013021103326,
  20211220: 11.52013021103326,
  20211221: 11.52013021103326,
  20211222: 11.52013021103326,
  20211223: 11.52013021103326,
  20211224: 11.52013021103326,
  20211227: 11.52013021103326,
  20211228: 11.520130211033262,
  20211229: 11.52013021103326,
  20211230: 11.520130211033258,
  20211231: 11.520130211033258,
  20220104: 11.520130211033258,
  20220105: 11.520130211033262,
  20220106: 11.520130211033262,
  20220107: 11.520130211033264,
  20220110: 11.520130211033262,
  20220111: 11.520130211033264,
  20220112: 11.520130211033266,
  20220113: 11.520130211033264,
  20220114: 11.520130211033264,
  20220117: 11.520130211033264,
  20220118: 11.520130211033264,
  20220119: 11.520130211033264,
  20220120: 11.520130211033264,
  20220121: 11.520130211033266,
  20220124: 11.520130211033266,
  20220125: 11.520130211033266,
  20220126: 11.520130211033266,
  20220127: 11.520130211033264,
  20220128: 11.520130211033264,
  20220207: 11.520130211033264,
  20220208: 11.520130211033266,
  20220209: 11.520130211033264,
  20220210: 11.520130211033262,
  20220211: 11.520130211033262,
  20220214: 11.520130211033262,
  20220215: 11.520130211033264,
  20220216: 11.520130211033264,
  20220217: 11.520130211033266,
  20220218: 11.520130211033264,
  20220221: 11.520130211033266,
  20220222: 11.520130211033264,
  20220223: 11.520130211033267,
  20220224: 11.520130211033264,
  20220225: 11.520130211033266,
  20220228: 11.520130211033267,
  20220301: 11.520130211033267,
  20220302: 11.520130211033267,
  20220303: 11.520130211033267,
  20220304: 11.520130211033267,
  20220307: 11.520130211033267,
  20220308: 11.520130211033269,
  20220309: 11.520130211033267,
  20220310: 11.520130211033267,
  20220311: 11.520130211033267,
  20220314: 11.520130211033266,
  20220315: 11.520130211033266,
  20220316: 11.520130211033266,
  20220317: 11.520130211033267,
  20220318: 11.520130211033264,
  20220321: 11.520130211033266,
  20220322: 11.520130211033266,
  20220323: 11.520130211033266,
  20220324: 11.520130211033266,
  20220325: 11.520130211033264,
  20220328: 11.520130211033262,
  20220329: 11.520130211033262,
  20220330: 11.520130211033264,
  20220331: 11.520130211033264,
  20220401: 11.520130211033266,
  20220406: 11.520130211033264,
  20220407: 11.520130211033264,
  20220408: 11.520130211033262,
  20220411: 11.520130211033264,
  20220412: 11.520130211033266,
  20220413: 11.520130211033264,
  20220414: 11.520130211033266,
  20220415: 11.520130211033266,
  20220418: 11.520130211033264,
  20220419: 11.520130211033266,
  20220420: 11.520130211033264,
  20220421: 11.520130211033262,
  20220422: 11.520130211033264,
  20220425: 11.520130211033266,
  20220426: 11.520130211033264,
  20220427: 11.520130211033264,
  20220428: 11.520130211033264,
  20220429: 11.520130211033264,
  20220505: 11.520130211033262,
  20220506: 11.520130211033264,
  20220509: 11.520130211033264,
  20220510: 11.520130211033266,
  20220511: 11.520130211033266,
  20220512: 11.520130211033266,
  20220513: 11.520130211033266,
  20220516: 11.520130211033266,
  20220517: 11.520130211033267,
  20220518: 11.520130211033264,
  20220519: 11.520130211033266,
  20220520: 11.520130211033266,
  20220523: 11.520130211033266,
  20220524: 11.520130211033269,
  20220525: 11.520130211033267,
  20220526: 11.520130211033269,
  20220527: 11.520130211033269,
  20220530: 11.520130211033269,
  20220531: 11.520130211033269,
  20220601: 11.520130211033267,
  20220602: 11.520130211033269,
  20220606: 11.520130211033269,
  20220607: 11.520130211033269,
  20220608: 11.520130211033269,
  20220609: 11.520130211033269,
  20220610: 11.520130211033269,
  20220613: 11.52013021103327,
  20220614: 11.520130211033269,
  20220615: 11.52013021103327,
  20220616: 11.52013021103327,
  20220617: 11.52013021103327,
  20220620: 11.52013021103327,
  20220621: 11.520130211033273,
  20220622: 11.520130211033273,
  20220623: 11.520130211033273,
  20220624: 11.520130211033274,
  20220627: 11.520130211033274,
  20220628: 11.520130211033276,
  20220629: 11.520130211033276,
  20220630: 11.520130211033276,
  20220701: 11.520130211033274,
  20220704: 11.520130211033278,
  20220705: 11.520130211033278,
  20220706: 11.520130211033278,
  20220707: 11.520130211033278,
  20220708: 11.520130211033276,
  20220711: 11.520130211033278,
  20220712: 11.520130211033278,
  20220713: 11.520130211033278,
  20220714: 11.520130211033274,
  20220715: 11.520130211033278,
  20220718: 11.520130211033278,
  20220719: 11.520130211033278,
  20220720: 11.520130211033276,
  20220721: 11.520130211033278,
  20220722: 11.520130211033278,
  20220725: 11.52013021103328,
  20220726: 11.52013021103328,
  20220727: 11.52013021103328,
  20220728: 11.52013021103328,
  20220729: 11.520130211033281,
  20220801: 11.52013021103328,
  20220802: 11.52013021103328,
  20220803: 11.52013021103328,
  20220804: 11.52013021103328,
  20220805: 11.520130211033281,
  20220808: 11.52013021103328,
  20220809: 11.52013021103328,
  20220810: 11.52013021103328,
  20220811: 11.520130211033278,
  20220812: 11.52013021103328,
  20220815: 11.520130211033278,
  20220816: 11.520130211033278,
  20220817: 11.520130211033281,
  20220818: 11.589356024568291,
  20220819: 11.589356024568291,
  20220822: 11.589356024568293,
  20220823: 11.589356024568293,
  20220824: 11.589356024568291,
  20220825: 11.58935602456829,
  20220826: 11.589356024568293,
  20220829: 11.589356024568291,
  20220830: 11.589356024568291,
  20220831: 11.589356024568291,
  20220901: 11.589356024568291,
  20220902: 11.589356024568293,
  20220905: 11.589356024568291,
  20220906: 11.589356024568291,
  20220907: 11.589356024568291,
  20220908: 11.589356024568291,
  20220909: 11.589356024568293,
  20220913: 11.589356024568293,
  20220914: 11.589356024568293,
  20220915: 11.589356024568295,
  20220916: 11.589356024568293,
  20220919: 11.589356024568293,
  20220920: 11.589356024568293,
  20220921: 11.589356024568291,
  20220922: 11.589356024568291,
  20220923: 11.589356024568291,
  20220926: 11.58935602456829,
  20220927: 11.58935602456829,
  20220928: 11.58935602456829,
  20220929: 11.589356024568293,
  20220930: 11.589356024568293,
  20221010: 11.589356024568295,
  20221011: 11.589356024568293,
  20221012: 11.589356024568295,
  20221013: 11.589356024568295,
  20221014: 11.589356024568295,
  20221017: 11.589356024568296,
  20221018: 11.589356024568298,
  20221019: 11.589356024568298,
  20221020: 11.589356024568296,
  20221021: 11.589356024568298,
  20221024: 11.5893560245683,
  20221025: 11.5893560245683,
  20221026: 11.5893560245683,
  20221027: 11.589356024568302,
  20221028: 11.589356024568303,
  20221031: 11.589356024568305,
  20221101: 11.589356024568305,
  20221102: 11.589356024568307,
  20221103: 11.58935602456831,
  20221104: 11.589356024568309,
  20221107: 11.589356024568312,
  20221108: 11.589356024568309,
  20221109: 11.58935602456831,
  20221110: 11.58935602456831,
  20221111: 11.58935602456831,
  20221114: 11.589356024568309,
  20221115: 11.589356024568309,
  20221116: 11.589356024568312,
  20221117: 11.58935602456831,
  20221118: 11.589356024568312,
  20221121: 11.589356024568314,
  20221122: 11.589356024568312,
  20221123: 11.589356024568312,
  20221124: 11.589356024568312,
  20221125: 11.589356024568312,
  20221128: 11.589356024568312,
  20221129: 11.589356024568316,
  20221130: 11.589356024568318,
  20221201: 11.589356024568318,
  20221202: 11.589356024568318,
  20221205: 11.589356024568321,
  20221206: 11.589356024568321,
  20221207: 11.589356024568321,
  20221208: 11.589356024568323,
  20221209: 11.589356024568323,
  20221212: 11.589356024568325,
  20221213: 11.589356024568323,
  20221214: 11.589356024568323,
  20221215: 11.589356024568323,
  20221216: 11.589356024568323,
  20221219: 11.589356024568321,
  20221220: 11.589356024568321,
  20221221: 11.589356024568321,
  20221222: 11.589356024568321,
  20221223: 11.589356024568321,
  20221226: 11.589356024568321,
  20221227: 11.58935602456832,
  20221228: 11.58935602456832,
  20221229: 11.58935602456832,
  20221230: 11.58935602456832,
  20230103: 11.589356024568321,
  20230104: 11.589356024568321,
  20230105: 11.58935602456832,
  20230106: 11.589356024568321,
  20230109: 11.58935602456832,
  20230110: 11.589356024568318,
  20230111: 11.589356024568318,
  20230112: 11.589356024568318,
  20230113: 11.589356024568318,
  20230116: 11.589356024568316,
  20230117: 11.589356024568318,
  20230118: 11.58935602456832,
  20230119: 11.589356024568318,
  20230120: 11.58935602456832,
  20230130: 11.58935602456832,
  20230131: 11.58935602456832,
  20230201: 11.58935602456832,
  20230202: 11.58935602456832,
  20230203: 11.589356024568321,
  20230206: 11.589356024568321,
  20230207: 11.589356024568321,
  20230208: 11.58935602456832,
  20230209: 11.58935602456832,
  20230210: 11.58935602456832,
  20230213: 11.589356024568321,
  20230214: 11.589356024568321,
  20230215: 11.589356024568321,
  20230216: 11.589356024568323,
  20230217: 11.589356024568323,
  20230220: 11.589356024568323,
  20230221: 11.589356024568321,
  20230222: 11.589356024568323,
  20230223: 11.589356024568323,
  20230224: 11.589356024568326,
  20230227: 11.589356024568321,
  20230228: 11.589356024568323,
  20230301: 11.589356024568323,
  20230302: 11.589356024568321,
  20230303: 11.589356024568321,
  20230306: 11.589356024568323,
  20230307: 11.589356024568321,
  20230308: 11.589356024568323,
  20230309: 11.589356024568323},
 'SZ.000001': {20210802: 111.9219663132372,
  20210803: 111.9219663132372,
  20210804: 111.92196631323719,
  20210805: 111.92196631323723,
  20210806: 111.92196631323722,
  20210809: 111.9219663132372,
  20210810: 111.92196631323719,
  20210811: 111.9219663132372,
  20210812: 111.9219663132372,
  20210813: 111.9219663132372,
  20210816: 111.92196631323722,
  20210817: 111.92196631323722,
  20210818: 111.92196631323722,
  20210819: 111.92196631323723,
  20210820: 111.92196631323722,
  20210823: 111.92196631323723,
  20210824: 111.92196631323723,
  20210825: 111.92196631323723,
  20210826: 111.92196631323722,
  20210827: 111.92196631323722,
  20210830: 111.9219663132372,
  20210831: 111.92196631323719,
  20210901: 111.92196631323719,
  20210902: 111.9219663132372,
  20210903: 111.92196631323719,
  20210906: 111.92196631323719,
  20210907: 111.9219663132372,
  20210908: 111.9219663132372,
  20210909: 111.9219663132372,
  20210910: 111.92196631323718,
  20210913: 111.92196631323719,
  20210914: 111.92196631323718,
  20210915: 111.92196631323718,
  20210916: 111.92196631323718,
  20210917: 111.92196631323716,
  20210922: 111.92196631323716,
  20210923: 111.92196631323716,
  20210924: 111.92196631323718,
  20210927: 111.92196631323716,
  20210928: 111.92196631323718,
  20210929: 111.92196631323716,
  20210930: 111.92196631323716,
  20211008: 111.92196631323718,
  20211011: 111.92196631323719,
  20211012: 111.92196631323715,
  20211013: 111.92196631323718,
  20211014: 111.92196631323716,
  20211015: 111.92196631323719,
  20211018: 111.92196631323716,
  20211019: 111.92196631323715,
  20211020: 111.92196631323715,
  20211021: 111.92196631323716,
  20211022: 111.92196631323718,
  20211025: 111.92196631323718,
  20211026: 111.92196631323719,
  20211027: 111.9219663132372,
  20211028: 111.92196631323718,
  20211029: 111.92196631323716,
  20211101: 111.92196631323718,
  20211102: 111.92196631323718,
  20211103: 111.92196631323718,
  20211104: 111.92196631323718,
  20211105: 111.92196631323718,
  20211108: 111.92196631323718,
  20211109: 111.92196631323718,
  20211110: 111.92196631323718,
  20211111: 111.92196631323716,
  20211112: 111.92196631323715,
  20211115: 111.92196631323714,
  20211116: 111.92196631323716,
  20211117: 111.92196631323712,
  20211118: 111.92196631323714,
  20211119: 111.92196631323715,
  20211122: 111.92196631323715,
  20211123: 111.92196631323714,
  20211124: 111.92196631323715,
  20211125: 111.92196631323712,
  20211126: 111.92196631323714,
  20211129: 111.92196631323712,
  20211130: 111.92196631323715,
  20211201: 111.92196631323715,
  20211202: 111.92196631323714,
  20211203: 111.92196631323714,
  20211206: 111.9219663132371,
  20211207: 111.92196631323709,
  20211208: 111.92196631323708,
  20211209: 111.92196631323708,
  20211210: 111.92196631323706,
  20211213: 111.92196631323708,
  20211214: 111.92196631323708,
  20211215: 111.92196631323708,
  20211216: 111.92196631323706,
  20211217: 111.92196631323709,
  20211220: 111.92196631323708,
  20211221: 111.92196631323709,
  20211222: 111.92196631323709,
  20211223: 111.92196631323708,
  20211224: 111.92196631323708,
  20211227: 111.9219663132371,
  20211228: 111.92196631323709,
  20211229: 111.9219663132371,
  20211230: 111.92196631323712,
  20211231: 111.9219663132371,
  20220104: 111.92196631323712,
  20220105: 111.92196631323709,
  20220106: 111.92196631323709,
  20220107: 111.92196631323709,
  20220110: 111.9219663132371,
  20220111: 111.9219663132371,
  20220112: 111.92196631323708,
  20220113: 111.9219663132371,
  20220114: 111.92196631323708,
  20220117: 111.92196631323706,
  20220118: 111.92196631323708,
  20220119: 111.92196631323709,
  20220120: 111.92196631323708,
  20220121: 111.92196631323705,
  20220124: 111.92196631323706,
  20220125: 111.92196631323705,
  20220126: 111.92196631323705,
  20220127: 111.92196631323706,
  20220128: 111.92196631323709,
  20220207: 111.92196631323705,
  20220208: 111.92196631323705,
  20220209: 111.92196631323705,
  20220210: 111.92196631323706,
  20220211: 111.92196631323705,
  20220214: 111.92196631323705,
  20220215: 111.92196631323706,
  20220216: 111.92196631323705,
  20220217: 111.92196631323705,
  20220218: 111.92196631323704,
  20220221: 111.92196631323704,
  20220222: 111.92196631323705,
  20220223: 111.92196631323705,
  20220224: 111.92196631323705,
  20220225: 111.92196631323705,
  20220228: 111.92196631323706,
  20220301: 111.92196631323708,
  20220302: 111.92196631323708,
  20220303: 111.92196631323709,
  20220304: 111.92196631323709,
  20220307: 111.92196631323708,
  20220308: 111.92196631323708,
  20220309: 111.92196631323709,
  20220310: 111.92196631323708,
  20220311: 111.92196631323708,
  20220314: 111.92196631323709,
  20220315: 111.92196631323709,
  20220316: 111.9219663132371,
  20220317: 111.92196631323709,
  20220318: 111.92196631323709,
  20220321: 111.9219663132371,
  20220322: 111.9219663132371,
  20220323: 111.92196631323708,
  20220324: 111.9219663132371,
  20220325: 111.9219663132371,
  20220328: 111.9219663132371,
  20220329: 111.92196631323709,
  20220330: 111.92196631323708,
  20220331: 111.92196631323706,
  20220401: 111.92196631323706,
  20220406: 111.92196631323708,
  20220407: 111.92196631323709,
  20220408: 111.92196631323708,
  20220411: 111.92196631323709,
  20220412: 111.92196631323708,
  20220413: 111.9219663132371,
  20220414: 111.92196631323709,
  20220415: 111.92196631323709,
  20220418: 111.9219663132371,
  20220419: 111.92196631323709,
  20220420: 111.9219663132371,
  20220421: 111.92196631323709,
  20220422: 111.9219663132371,
  20220425: 111.92196631323708,
  20220426: 111.92196631323706,
  20220427: 111.92196631323708,
  20220428: 111.92196631323708,
  20220429: 111.92196631323706,
  20220505: 111.92196631323706,
  20220506: 111.92196631323706,
  20220509: 111.92196631323708,
  20220510: 111.92196631323706,
  20220511: 111.92196631323706,
  20220512: 111.92196631323706,
  20220513: 111.92196631323706,
  20220516: 111.92196631323704,
  20220517: 111.92196631323702,
  20220518: 111.92196631323702,
  20220519: 111.92196631323704,
  20220520: 111.92196631323702,
  20220523: 111.92196631323704,
  20220524: 111.92196631323702,
  20220525: 111.92196631323702,
  20220526: 111.92196631323702,
  20220527: 111.92196631323704,
  20220530: 111.92196631323701,
  20220531: 111.92196631323702,
  20220601: 111.92196631323701,
  20220602: 111.92196631323701,
  20220606: 111.921966313237,
  20220607: 111.92196631323702,
  20220608: 111.92196631323702,
  20220609: 111.92196631323702,
  20220610: 111.921966313237,
  20220613: 111.92196631323701,
  20220614: 111.921966313237,
  20220615: 111.921966313237,
  20220616: 111.92196631323701,
  20220617: 111.92196631323698,
  20220620: 111.92196631323698,
  20220621: 111.92196631323695,
  20220622: 111.92196631323695,
  20220623: 111.92196631323696,
  20220624: 111.92196631323696,
  20220627: 111.92196631323696,
  20220628: 111.92196631323698,
  20220629: 111.92196631323698,
  20220630: 111.92196631323696,
  20220701: 111.92196631323696,
  20220704: 111.92196631323694,
  20220705: 111.92196631323694,
  20220706: 111.92196631323694,
  20220707: 111.92196631323694,
  20220708: 111.92196631323695,
  20220711: 111.92196631323694,
  20220712: 111.92196631323694,
  20220713: 111.92196631323694,
  20220714: 111.92196631323695,
  20220715: 111.92196631323694,
  20220718: 111.92196631323698,
  20220719: 111.92196631323698,
  20220720: 111.92196631323698,
  20220721: 111.92196631323696,
  20220722: 113.93621140338131,
  20220725: 113.93621140338131,
  20220726: 113.93621140338131,
  20220727: 113.93621140338131,
  20220728: 113.93621140338131,
  20220729: 113.93621140338131,

In [24]:
#计算sh600085的k线的收盘价的后复权价
sh600085 = kline_data[kline_data["symbol"]=="SH.600085"].copy()
sh600085['close_fq'] = sh600085.apply(lambda x: int(round(factor['SH.600085'][x['date']]*x['close'],-2)),axis=1)
sh600085.head()

,date,time,pre_close,open,high,low,close,volume,turnover,open_interest,pre_settle_price,settle_price,symbol,close_fq
1,20221101,150000,487500,476000,481800,462800,473000,22655583,1065165972,0,0,0,SH.600085,5481800
3,20221102,150000,473000,482500,515100,474500,495800,25116193,1241642059,0,0,0,SH.600085,5746000
5,20221103,150000,495800,490300,495400,480800,486800,11975890,583286659,0,0,0,SH.600085,5641700
7,20221104,150000,486800,483200,506700,481500,498000,11213095,554260198,0,0,0,SH.600085,5771500
9,20221107,150000,498000,499800,500000,486000,489800,11446232,561484304,0,0,0,SH.600085,5676500